### ISSUE TITLE
Not working on Oppo R5s

### ISSUE THREAD

**Issue by tdaliviu** [omnirom/android_device_oppo_r5#1]
Previously I've had the Oppo R5 and TWRP worked a charm on it. Recently I've switched to Oppo R5s, which essentially is the same thing +more RAM (3GB) and more ROM (32GB). After flashing TWRP to this device, I'm stuck at the boot screen.

If it helps, it seems that the official images for these two devices are the same. Even the device name hasn't changed - it's R8106 (well, at least the EU version). Compared build.prop from R5s and R5 - same stuff, no differences.

Also, I'd be willing to cooperate as I have the device and am technically savvy ;)

**Comment by Entropy512** [comment]
My guess is it's related to the DTB issues that caused r5 to take months to
get support.  My guess is that the DTB entry for this specific device is
missing.

Maxwen might have a better idea of how you might get this information from
a stock build or stock images...

**Comment by tdaliviu** [comment]
Yeah, so boot images for both R5 and R5s are the same - compared the yanked out binaries. That probably means the DTBs in the original images include R5s, while the one in the TWRP image - doesn't. I've done some play-and-dance with DTBs in the past - not the most satisfying experience :)

**Comment by Entropy512** [comment]
Oppo's DTBs are strange/nonstandard -
https://github.com/omnirom/android_device_oppo_r5/commit/e5ed7e33365889779bb84610a41e6bfe9c6dae02

My guess is that R5 and R5s have different oppoId - stock DTBs have
datasets for both of these oppoIds in them but TWRP only has the R5 -
again, that's just a guess

**Comment by tdaliviu** [comment]
Would yanking the DTB from a factory boot image and using the dtb.img to
build TWRP help?

**Comment by maxwen** [comment]
Yes its a missing dts issue
We only use oppo R5 stock kernel oppo ids and nothing has changed in there
Most prolly the R5S has also an oppo id of 15xxx (compared to 14xxx) like the R7 

EDIT: lets continue this on XDA :)

**Comment by tdaliviu** [comment]
I'll close this, since as I understood, there's nothing to be done. I guess anything that could be done, should be done in a separate repo specifically for the R5s.

**Comment by maxwen** [comment]
Please see XDA for further steps :)
